spring:
  application:
    name: mall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://123.56.166.56:3308/mall_oms?useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
